#!/usr/bin/env node
// Fallback digest builder that runs without an LLM. Consumes the outputs of
// poll-upstreams.mjs, build-context.mjs, and flag-skills.mjs, and writes a
// single markdown document to digest.md plus a short PR body to pr-body.md.
//
// The LLM-synthesized path overwrites digest.md with a richer version; this
// script is both the Phase-1 baseline and the fallback when ANTHROPIC_API_KEY
// is not configured.

import fs from 'node:fs/promises';
import path from 'node:path';

const REPO_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..');
const POLL = path.join(REPO_ROOT, 'context', 'poll.json');
const REPOS_DIR = path.join(REPO_ROOT, 'context', 'repos');
const FLAGGED = path.join(REPO_ROOT, 'context', 'flagged-skills.json');
const DIGEST_OUT = path.join(REPO_ROOT, 'digest.md');
const PR_BODY_OUT = path.join(REPO_ROOT, 'pr-body.md');

const EMOJI_SECTIONS = [
  ['### 🛑', 'Breaking', 'breaking'],
  ['### 🚩', 'Deprecations', 'deprecation'],
  ['### 🚀', 'New components', 'new'],
  ['### 💡', 'Enhancements', 'enhancement'],
  ['### 🧰', 'Bug fixes', 'fix'],
];

function classifyChangelog(section) {
  if (!section) return { impact: 'unknown', summary: null };
  const counts = {};
  for (const [marker, name] of EMOJI_SECTIONS) {
    const rx = new RegExp(`^${marker}[^\\n]*$`, 'gmi');
    const matches = section.match(rx) ?? [];
    if (matches.length) counts[name] = matches.length;
  }
  const impact = section.includes('🛑') ? 'breaking'
    : section.includes('🚩') ? 'deprecation'
    : section.includes('🚀') ? 'new'
    : section.includes('💡') ? 'enhancement'
    : 'fix';
  return { impact, counts };
}

function impactBadge(impact) {
  return ({
    breaking: '🔴 breaking',
    deprecation: '🟡 deprecation',
    stability: '🟡 stability',
    new: '🔵 new',
    enhancement: '🟢 enhancement',
    fix: '🟢 fix',
    unknown: '⚪ unknown',
  })[impact] ?? '⚪';
}

async function readJson(p, fallback) {
  try {
    return JSON.parse(await fs.readFile(p, 'utf8'));
  } catch (err) {
    if (err.code === 'ENOENT') return fallback;
    throw err;
  }
}

function clip(text, n) {
  if (!text) return '';
  return text.length <= n ? text : text.slice(0, n) + '\n\n…(truncated)';
}

async function main() {
  const poll = await readJson(POLL, { repos: {} });
  const flagged = (await readJson(FLAGGED, { flagged: [] })).flagged;

  const changedRepos = [];
  for (const [repo, row] of Object.entries(poll.repos)) {
    if (row.error || row.first_poll) continue;
    if (!row.release_changed && !row.commit_changed) continue;
    const filename = repo.replace('/', '__') + '.json';
    const ctx = await readJson(path.join(REPOS_DIR, filename), null);
    const classification = classifyChangelog(ctx?.changelog_section ?? ctx?.release_body ?? '');
    changedRepos.push({ repo, row, ctx, classification });
  }

  // --- digest.md ---
  const tier = poll.tier ?? 'unknown';
  const polledAt = poll.polled_at ?? new Date().toISOString();
  const date = polledAt.slice(0, 10);

  const lines = [];
  lines.push(`# OpenTelemetry upstream digest — ${tier} — ${date}`);
  lines.push('');
  lines.push(`_Auto-generated by \`.github/workflows/upstream-${tier}*.yml\`. Human review required before merging any suggested skill edits._`);
  lines.push('');

  if (changedRepos.length === 0) {
    lines.push('No upstream changes detected in this run.');
  } else {
    lines.push('## Summary');
    lines.push('');
    lines.push('| Repo | Old → New | Impact | Files touched | Skill refs flagged |');
    lines.push('|------|-----------|--------|---------------|--------------------|');
    for (const { repo, row, ctx, classification } of changedRepos) {
      const oldV = row.prior.last_release ?? '(main)';
      const newV = row.current.last_release ?? `${(row.current.last_commit_sha ?? '').slice(0, 7)}@main`;
      const fileCount = ctx?.files?.length ?? 0;
      const skillCount = flagged.filter((f) =>
        f.matched_files.some((m) => m.repo === repo),
      ).length;
      lines.push(`| ${repo} | ${oldV} → ${newV} | ${impactBadge(classification.impact)} | ${fileCount} | ${skillCount} |`);
    }
    lines.push('');

    lines.push('## Flagged skill references');
    lines.push('');
    if (flagged.length === 0) {
      lines.push('_No skill references flagged by the upstream-map mapping._');
    } else {
      for (const f of flagged) {
        const star = f.priority === 'critical' ? ' ⚠️ **critical**' : '';
        lines.push(`- **${f.skill}**${star} — ${f.match_count} matching file(s); topics: ${f.topics.join(', ') || '(none)'}`);
        for (const m of f.matched_files.slice(0, 5)) {
          lines.push(`  - \`${m.repo}\` · \`${m.path}\` (matched \`${m.matched_pattern}\`)`);
        }
        if (f.matched_files_truncated) lines.push('  - _…additional matches truncated_');
      }
    }
    lines.push('');

    lines.push('## Per-repo detail');
    lines.push('');
    for (const { repo, row, ctx, classification } of changedRepos) {
      const oldV = row.prior.last_release ?? '(main)';
      const newV = row.current.last_release ?? `${(row.current.last_commit_sha ?? '').slice(0, 7)}@main`;
      lines.push(`<details><summary><strong>${repo}</strong> — ${oldV} → ${newV} — ${impactBadge(classification.impact)}</summary>`);
      lines.push('');
      if (row.current.last_release_url) {
        lines.push(`Release: [${row.current.last_release}](${row.current.last_release_url}) · published ${row.current.last_release_published_at}`);
        lines.push('');
      }
      if (ctx?.changelog_section) {
        lines.push('**Changelog section**');
        lines.push('');
        lines.push('```markdown');
        lines.push(clip(ctx.changelog_section, 6000));
        lines.push('```');
        lines.push('');
      } else if (ctx?.release_body) {
        lines.push('**Release body**');
        lines.push('');
        lines.push('```markdown');
        lines.push(clip(ctx.release_body, 6000));
        lines.push('```');
        lines.push('');
      }
      if (ctx?.files?.length) {
        lines.push(`**Files touched:** ${ctx.files.length}${ctx.compare_truncated ? ' (truncated)' : ''}`);
        lines.push('');
        lines.push('```');
        for (const f of ctx.files.slice(0, 40)) {
          lines.push(`${f.status.padEnd(10)} ${f.path}`);
        }
        if (ctx.files.length > 40) lines.push(`… ${ctx.files.length - 40} more`);
        lines.push('```');
        lines.push('');
      }
      lines.push('</details>');
      lines.push('');
    }

    lines.push('## Maintainer checklist');
    lines.push('');
    lines.push('- [ ] Review flagged skill references for needed edits.');
    lines.push('- [ ] Confirm the state-bump PR matches upstream heartbeat.');
    lines.push('- [ ] Escalate any 🔴 breaking / ⚠️ critical rows to a follow-up issue.');
  }

  // Enforce GitHub's ~65 KB issue body limit.
  const MAX = 60 * 1024;
  let digest = lines.join('\n') + '\n';
  if (digest.length > MAX) {
    digest = digest.slice(0, MAX - 200) + '\n\n_…digest truncated — see `context/` artifacts for the full payload._\n';
  }
  await fs.writeFile(DIGEST_OUT, digest);

  // --- pr-body.md ---
  const pr = [];
  pr.push(`Automated upstream refresh (${tier}) at ${polledAt}.`);
  pr.push('');
  if (changedRepos.length === 0) {
    pr.push('No upstream changes detected; PR bumps the heartbeat state only.');
  } else {
    pr.push(`Heartbeat updates for ${changedRepos.length} repo(s):`);
    for (const { repo, row } of changedRepos) {
      const oldV = row.prior.last_release ?? '(main)';
      const newV = row.current.last_release ?? `${(row.current.last_commit_sha ?? '').slice(0, 7)}@main`;
      pr.push(`- ${repo}: ${oldV} → ${newV}`);
    }
    pr.push('');
    const critical = flagged.filter((f) => f.priority === 'critical');
    if (critical.length > 0) {
      pr.push(`⚠️ **critical** skill references flagged: ${critical.map((c) => c.skill).join(', ')}`);
      pr.push('');
    }
    pr.push('See the accompanying digest issue for per-repo changelog detail.');
  }
  await fs.writeFile(PR_BODY_OUT, pr.join('\n') + '\n');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
